name: New Code Freeze
on:
    release:
        types: [released]

permissions: {}

jobs:
    verify-release:
        name: 'Verify if the release is a major version release, that ends with .0'
        runs-on: ubuntu-20.04
        outputs:
            run: ${{ steps.verify.outputs.run }}
        steps:
            - name: Verify release
              id: verify
              uses: actions/github-script@v6
              with:
                  script: |
                      const event = context.payload;
                      const release = event.release;

                      if (release.tag_name.endsWith('.0')) {
                          core.setOutput('run', 'true');
                      } else {
                          core.setOutput('run', 'false');
                      }

    verify-if-any-pr-is-left-open:
        name: 'Verify if any PR is left open by author:app/github-actions'
        needs: verify-release
        runs-on: ubuntu-20.04
        steps:
            - name: Verify if any PR is left open by author:app/github-actions
              uses: actions/github-script@v6
              with:
                  script: |
                      const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
                      const prs = await github.rest.pulls.list({ owner, repo, state: 'open', author: 'app/github-actions' });
                      if (prs.data.length > 0) {
                          core.setFailed(`Found ${prs.data.length} open PRs from github-actions bot. Please close them before proceeding.`);
                      }

            - name: Notify Slack on failure
              if: ${{ failure() }}
              uses: archive/github-actions-slack@v2.0.0
              with:
                  slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
                  slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
                  slack-text: |
                      :ice_cube: Code Freeze workflow failed.
                      :warning-8c: There are PRs left open by `app/github-actions` bot. Please close them and re-run the workflow.
    
    prep-for-code-freeze:
        name: 'Prepare for code freeze - generate next release branch and milestone'
        if: needs.verify-release.outputs.run == 'true'
        needs: verify-release
        runs-on: ubuntu-20.04
        outputs:
            nextReleaseBranch: ${{ steps.extract-version.outputs.nextReleaseBranch }}
            nextMajorMilestone: ${{ steps.extract-version.outputs.nextMajorMilestone }}
        steps:
            - name: Extract version from release tag
              id: extract-version
              uses: actions/github-script@v6
              with:
                  script: |
                      const event = context.payload;
                      const currentTag = event.release.tag_name;
                      const [major, minor, patch] = currentTag.split('.').map(Number);

                      let nextMajor = major;
                      let nextMinor = minor + 1;
                      if (nextMinor > 9) {
                          nextMajor += 1;
                          nextMinor = 0;
                      }

                      const nextReleaseBranch = `release/${nextMajor}.${nextMinor}`;
                      const nextMajorMilestone = `${nextMajor}.${nextMinor}.0`;
                      core.setOutput('nextReleaseBranch', nextReleaseBranch);
                      core.setOutput('nextMajorMilestone', nextMajorMilestone);
                      console.log(`Next release branch: ${nextReleaseBranch}`);
                      console.log(`Next milestone: ${nextMajorMilestone}`);
    
    create-code-freeze-branch-and-milestone:
        name: 'Create the code freeze branch and milestone for next release'
        needs: prep-for-code-freeze
        runs-on: ubuntu-20.04
        permissions:
          issues: write
          contents: write
        steps:
            - name: Fetch all the branches
              uses: actions/checkout@v3
              with:
                ref: trunk

            - name: Create code freeze branch out of trunk
              run: |
                  git checkout trunk
                  git checkout -b $RELEASE_BRANCH
              env:
                RELEASE_BRANCH: ${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}

            - name: Push the new branch to the remote repository
              run: git push origin $RELEASE_BRANCH
              env:
                RELEASE_BRANCH: ${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}

            - name: Create milestone in Github repository
              uses: actions/github-script@v6
              with:
                  script: |
                      const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
                      await github.rest.issues.createMilestone({
                          owner: owner,
                          repo: repo,
                          title: process.env.MILESTONE
                      });
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                MILESTONE: ${{ needs.prep-for-code-freeze.outputs.nextMajorMilestone }}

            - name: Notify Slack on success
              if: ${{ success() }}
              uses: archive/github-actions-slack@v2.0.0
              with:
                  slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
                  slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
                  slack-text: |
                      :ice_cube: Code Freeze completed for `${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}`. You can raise a code freeze exception if you need something to be included in this release.
                  slack-optional-unfurl_links: false
                  slack-optional-unfurl_media: false

            - name: Notify Slack on failure
              if: ${{ failure() }}
              uses: archive/github-actions-slack@v2.0.0
              with:
                  slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
                  slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
                  slack-text: |
                      :warning-8c: Code freeze failed for `${{ needs.prep-for-code-freeze.outputs.nextReleaseBranch }}`. Please check the logs for more details. Workflow run: `${{ github.workflow_run.html_url }}`
